"""Human-in-the-loop publishing of reviews to GitHub with stale-PR and duplicate protection."""
from __future__ import annotations

import hashlib
import json
import logging
import re
from dataclasses import dataclass, field
from typing import Any, Literal

from .db import Database
from .diff_parser import DiffIndex
from .github_client import GitHubClient
from .schemas import Issue, PRRef, ReviewResult

log = logging.getLogger(__name__)
_MENTION = re.compile(r"(?<![\w`])@([A-Za-z0-9][A-Za-z0-9-]*(?:/[A-Za-z0-9_-]+)?)")


class PublishError(Exception):
    pass


class StaleReviewError(PublishError):
    def __init__(self, reviewed_sha: str, current_sha: str) -> None:
        super().__init__(f"The PR changed after this review was generated (reviewed {reviewed_sha[:8]}, now {current_sha[:8]}). "
                         "Findings may be stale — run a refreshed review before publishing.")
        self.reviewed_sha, self.current_sha = reviewed_sha, current_sha


class DuplicatePublicationError(PublishError):
    def __init__(self, url: str | None) -> None:
        super().__init__("This exact review content was already published to this PR" + (f": {url}" if url else "") + ".")
        self.url = url


class ConfirmationError(PublishError):
    pass


@dataclass
class PublishOptions:
    mode: Literal["overview", "inline"] = "overview"
    issue_ids: list[str] | None = None  # None → every issue with included=True
    include_test: bool = False
    body_override: str | None = None


@dataclass
class PublishPlan:
    ref: PRRef
    head_sha: str
    mode: str
    body: str
    inline_comments: list[dict[str, Any]] = field(default_factory=list)
    inline_issue_ids: list[str] = field(default_factory=list)
    overview_issue_ids: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    @property
    def content_hash(self) -> str:
        payload = json.dumps({"r": self.ref.slug, "sha": self.head_sha, "b": self.body, "c": self.inline_comments}, sort_keys=True)
        return hashlib.sha256(payload.encode()).hexdigest()


def neutralize(text: str) -> str:
    """Stop AI/repo text from pinging users or teams when posted to GitHub."""
    return _MENTION.sub(lambda m: "@​" + m.group(1), text)


def _fence(code: str, lang: str = "") -> str:
    ticks = max([len(m) for m in re.findall(r"`+", code)] + [2]) + 1
    f = "`" * ticks
    return f"{f}{lang}\n{code.rstrip()}\n{f}"


_SEV_ICON = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵"}


def render_issue_md(i: Issue, heading: bool = True) -> str:
    loc = f"`{i.file}`" + (f" line {i.line}" if i.line else "")
    parts = [f"{_SEV_ICON[i.severity]} **{i.severity.upper()} · {i.category}** — {neutralize(i.title)}" if heading else ""]
    if heading:
        parts.append(f"{loc} · _{i.verification_status}_")
    parts.append(neutralize(i.explanation))
    if i.evidence:
        parts.append("Evidence:\n" + _fence(i.evidence))
    if i.suggested_fix:
        parts.append("**Suggested fix:** " + neutralize(i.suggested_fix))
    if i.suggested_code:
        parts.append(_fence(i.suggested_code))
    return "\n\n".join(p for p in parts if p)


def render_review_markdown(result: ReviewResult, ref: PRRef, overview: list[Issue], inline_count: int,
                           include_test: bool) -> str:
    m = result.metadata
    out = [f"## ZeroPulse PR Review — risk: **{result.overall_risk}**", "", neutralize(result.summary or "_No summary._")]
    if overview:
        out += ["", "### Findings"]
        for n, i in enumerate(overview, 1):
            out += ["", f"**{n}.** " + render_issue_md(i)]
    if inline_count:
        out += ["", f"_{inline_count} finding(s) are attached as inline comments on the changed lines._"]
    if not overview and not inline_count:
        out += ["", "_No findings were selected for publication._"]
    if include_test and result.test_file:
        t = result.test_file
        status = {"not_run": "not executed", "passed": "passed in sandbox", "failed": "failed in sandbox", "error": "execution error"}[t.execution_status]
        out += ["", f"<details><summary>Proposed test: <code>{t.filename}</code> ({t.framework}, {status})</summary>", "",
                neutralize(t.purpose), ""]
        if t.needs_verification:
            out += ["> ⚠️ Draft — requires verification: " + neutralize("; ".join(t.verification_notes[:3])), ""]
        out += [_fence(t.content, t.language), "", "</details>"]
    if result.limitations:
        out += ["", "<details><summary>Review limitations</summary>", ""] + [f"- {neutralize(l)}" for l in result.limitations] + ["", "</details>"]
    out += ["", "---", f"_AI-generated by ZeroPulse PR Review Agent ({m.provider}: {m.model}) at `{m.head_sha[:8]}`. "
            "Verify before acting; not a substitute for human review._"]
    return "\n".join(out)


def build_plan(ref: PRRef, result: ReviewResult, options: PublishOptions, current_index: DiffIndex | None,
               head_sha: str) -> PublishPlan:
    chosen = [i for i in result.issues if (i.id in options.issue_ids if options.issue_ids is not None else i.included)]
    inline: list[Issue] = []
    overview: list[Issue] = []
    warnings: list[str] = []
    for i in chosen:
        can_inline = (options.mode == "inline" and current_index is not None and i.line is not None
                      and i.verification_status == "verified" and (fd := current_index.get(i.file)) is not None
                      and fd.is_valid_location(i.line, i.side))
        (inline if can_inline else overview).append(i)
    if options.mode == "inline" and len(overview) and chosen:
        warnings.append(f"{len(overview)} finding(s) cannot be anchored to a verified diff line and are included in the overview instead.")
    comments = [{"path": i.file, "line": i.line, "side": i.side, "body": render_issue_md(i) + f"\n\n<sub>ZeroPulse · {i.id}</sub>"}
                for i in inline]
    body = options.body_override if options.body_override is not None else render_review_markdown(
        result, ref, overview, len(inline), options.include_test)
    if not body.strip():
        raise PublishError("The review body is empty.")
    if len(body) > 60000:
        raise PublishError("The review body exceeds GitHub's size limit; deselect findings or the test file.")
    return PublishPlan(ref=ref, head_sha=head_sha, mode=options.mode, body=body, inline_comments=comments,
                       inline_issue_ids=[i.id for i in inline], overview_issue_ids=[i.id for i in overview], warnings=warnings)


@dataclass
class PublicationRecord:
    github_review_id: int
    url: str
    inline_comments: int


class Publisher:
    def __init__(self, github: GitHubClient, db: Database) -> None:
        self.github, self.db = github, db

    def prepare(self, review_id: str, options: PublishOptions) -> PublishPlan:
        """Re-fetch the PR, detect staleness, and build the exact content that would be published."""
        row = self.db.get_review(review_id)
        result = self.db.get_result(review_id)
        if not row or not result:
            raise PublishError("Review not found or has no completed result.")
        ref = PRRef(owner=row["repo"].split("/")[0], repo=row["repo"].split("/")[1], number=row["pr_number"])
        current = self.github.fetch_pr(ref)
        reviewed = result.metadata.head_sha or row["head_sha"]
        if current.head_sha != reviewed:
            self.db.mark_stale(review_id)
            raise StaleReviewError(reviewed, current.head_sha)
        if current.state != "open":
            raise PublishError(f"The pull request is {current.state}; not publishing.")
        return build_plan(ref, result, options, DiffIndex(current.files), current.head_sha)

    def publish(self, review_id: str, plan: PublishPlan, confirm_slug: str) -> PublicationRecord:
        if confirm_slug.strip() != plan.ref.slug:
            raise ConfirmationError(f"Confirmation mismatch: type exactly {plan.ref.slug} to publish.")
        existing = self.db.find_publication(plan.ref.full_name, plan.ref.number, plan.content_hash)
        if existing:
            raise DuplicatePublicationError(existing.get("url"))
        latest = self.github.get_head_sha(plan.ref)  # last-moment staleness check
        if latest != plan.head_sha:
            self.db.mark_stale(review_id)
            raise StaleReviewError(plan.head_sha, latest)
        rid, url = self.github.create_review(plan.ref, plan.head_sha, plan.body, plan.inline_comments)
        self.db.record_publication(review_id=review_id, repo=plan.ref.full_name, pr_number=plan.ref.number,
                                   head_sha=plan.head_sha, mode=plan.mode, content_hash=plan.content_hash,
                                   github_review_id=rid, url=url, inline_comments=len(plan.inline_comments))
        return PublicationRecord(rid, url, len(plan.inline_comments))
